services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - 5432:5432
  bot:
    image: bot-dev:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: secret
      DB_NAME: mydatabase
