name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run checkstyle
        uses: dbelyaev/action-checkstyle@v1.16.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          workdir: ./
          checkstyle_config: ./checkstyle.xml
          level: error
          filter_mode: nofilter